services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=ola
    volumes:
      - /var/lib/postgresql/data
  mongodb:
    image: mongo    
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=ola
    ports:
      - 27017:27017
    volumes:
      - /var/lib/mongodb/data  